import { prisma } from "../../server/utils/db";
import bcrypt from "bcrypt";
import * as mm from "music-metadata";

async function getAudioDuration(url: string): Promise<number> {
  try {
    const response = await fetch(url);
    if (!response.ok || !response.body) return 0;
    const metadata = await mm.parseWebStream(
      response.body,
      { mimeType: "audio/mpeg" },
      { duration: true },
    );
    return Math.round(metadata.format.duration ?? 0);
  } catch {
    console.warn(`Could not fetch duration for ${url}, defaulting to 0`);
    return 0;
  }
}

export async function seedBeats() {
  // Create test producer profiles
  const hashedPassword = await bcrypt.hash("password123", 10);

  const producer1 = await prisma.user.upsert({
    where: { email: "producer1@beatstack.com" },
    update: {},
    create: {
      email: "producer1@beatstack.com",
      password: hashedPassword,
      isVerified: true,
      profile: {
        create: {
          firstName: "Mike",
          lastName: "Beats",
          username: "mikebeats",
          role: "PRODUCER",
          bio: "Lo-Fi & Chill beat producer",
        },
      },
    },
    include: { profile: true },
  });

  const producer2 = await prisma.user.upsert({
    where: { email: "producer2@beatstack.com" },
    update: {},
    create: {
      email: "producer2@beatstack.com",
      password: hashedPassword,
      isVerified: true,
      profile: {
        create: {
          firstName: "Sarah",
          lastName: "Trap",
          username: "sarahtrap",
          role: "PRODUCER",
          bio: "Trap & Drill specialist",
        },
      },
    },
    include: { profile: true },
  });

  // Create beats
  const beatDefinitions = [
    {
      title: "Midnight Thoughts",
      producerId: producer1.profile!.id,
      genre: "Lo-Fi",
      bpm: 85,
      key: "C",
      duration: 156,
      tags: ["Chill", "Melodic", "Smooth"],
      priceBasic: 29.99,
      pricePremium: 49.99,
      priceExclusive: 199.99,
      coverImage: "https://picsum.photos/seed/beat1/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      description: "A smooth lo-fi beat perfect for late night vibes",
      isPublished: true,
    },
    {
      title: "Trap Heat",
      producerId: producer2.profile!.id,
      genre: "Trap",
      bpm: 140,
      key: "D#m",
      duration: 180,
      tags: ["Hard", "808", "Dark"],
      priceBasic: 34.99,
      pricePremium: 59.99,
      priceExclusive: 249.99,
      coverImage: "https://picsum.photos/seed/beat2/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      description: "Heavy hitting trap beat with punchy 808s",
      isPublished: true,
    },
    {
      title: "Summer Vibes",
      producerId: producer1.profile!.id,
      genre: "Pop",
      bpm: 120,
      key: "G",
      duration: 195,
      tags: ["Happy", "Upbeat", "Melodic"],
      priceBasic: 24.99,
      pricePremium: 44.99,
      priceExclusive: 179.99,
      coverImage: "https://picsum.photos/seed/beat3/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
      description: "Uplifting pop beat with summer vibes",
      isPublished: true,
    },
    {
      title: "Dark Energy",
      producerId: producer2.profile!.id,
      genre: "Drill",
      bpm: 138,
      key: "Am",
      duration: 165,
      tags: ["Dark", "Aggressive", "808"],
      priceBasic: 39.99,
      pricePremium: 64.99,
      priceExclusive: 299.99,
      coverImage: "https://picsum.photos/seed/beat4/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
      description: "Aggressive drill beat with dark atmosphere",
      isPublished: true,
    },
    {
      title: "R&B Smooth",
      producerId: producer1.profile!.id,
      genre: "R&B",
      bpm: 95,
      key: "F",
      duration: 210,
      tags: ["Smooth", "Melodic"],
      priceBasic: 32.99,
      pricePremium: 54.99,
      priceExclusive: 229.99,
      coverImage: "https://picsum.photos/seed/beat5/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
      description: "Smooth R&B beat with soulful melodies",
      isPublished: true,
    },
    {
      title: "Boom Bap Classic",
      producerId: producer2.profile!.id,
      genre: "Boom Bap",
      bpm: 90,
      key: "Em",
      duration: 175,
      tags: ["Classic", "Hip-Hop"],
      priceBasic: 27.99,
      pricePremium: 47.99,
      priceExclusive: 189.99,
      coverImage: "https://picsum.photos/seed/beat6/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
      description: "Old school boom bap with classic vibes",
      isPublished: true,
    },
    {
      title: "Chillwave Dreams",
      producerId: producer1.profile!.id,
      genre: "Lo-Fi",
      bpm: 88,
      key: "A",
      duration: 160,
      tags: ["Relaxing", "Ambient"],
      priceBasic: 25.99,
      pricePremium: 45.99,
      priceExclusive: 199.99,
      coverImage: "https://picsum.photos/seed/beat7/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
      description: "Dreamy lo-fi beat for chill moments",
      isPublished: true,
    },
    {
      title: "Urban Flow",
      producerId: producer2.profile!.id,
      genre: "Hip-Hop",
      bpm: 92,
      key: "C#m",
      duration: 180,
      tags: ["Groovy", "Modern"],
      priceBasic: 30.99,
      pricePremium: 50.99,
      priceExclusive: 209.99,
      coverImage: "https://picsum.photos/seed/beat8/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
      description: "Modern hip-hop beat with urban vibes",
      isPublished: true,
    },
    {
      title: "Synthwave Rush",
      producerId: producer1.profile!.id,
      genre: "Synthwave",
      bpm: 128,
      key: "F#m",
      duration: 200,
      tags: ["Retro", "Energetic"],
      priceBasic: 35.99,
      pricePremium: 55.99,
      priceExclusive: 249.99,
      coverImage: "https://picsum.photos/seed/beat9/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
      description: "Energetic synthwave beat with retro vibes",
      isPublished: true,
    },
    {
      title: "Acoustic Serenity",
      producerId: producer2.profile!.id,
      genre: "Acoustic",
      bpm: 75,
      key: "D",
      duration: 220,
      tags: ["Calm", "Peaceful"],
      priceBasic: 28.99,
      pricePremium: 48.99,
      priceExclusive: 189.99,
      coverImage: "https://picsum.photos/seed/beat10/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
      description: "Peaceful acoustic beat for relaxing moments",
      isPublished: true,
    },
    {
      title: "Future Bass Drop",
      producerId: producer1.profile!.id,
      genre: "Future Bass",
      bpm: 140,
      key: "G#m",
      duration: 190,
      tags: ["Energetic", "Bass"],
      priceBasic: 40.99,
      pricePremium: 60.99,
      priceExclusive: 259.99,
      coverImage: "https://picsum.photos/seed/beat11/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      description: "High-energy future bass beat",
      isPublished: true,
    },
    {
      title: "Lo-Fi Chill",
      producerId: producer1.profile!.id,
      genre: "Lo-Fi",
      bpm: 87,
      key: "B",
      duration: 150,
      tags: ["Relaxing", "Chill"],
      priceBasic: 22.99,
      pricePremium: 42.99,
      priceExclusive: 199.99,
      coverImage: "https://picsum.photos/seed/beat12/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
      description: "Relaxing lo-fi beat for study sessions",
      isPublished: true,
    },
    {
      title: "Trap Vibes",
      producerId: producer2.profile!.id,
      genre: "Trap",
      bpm: 145,
      key: "E",
      duration: 170,
      tags: ["Hard", "808"],
      priceBasic: 35.99,
      pricePremium: 55.99,
      priceExclusive: 249.99,
      coverImage: "https://picsum.photos/seed/beat13/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
      description: "Hard-hitting trap beat with deep bass",
      isPublished: true,
    },
    {
      title: "Jazz Hop",
      producerId: producer1.profile!.id,
      genre: "Jazz",
      bpm: 95,
      key: "C#m",
      duration: 180,
      tags: ["Smooth", "Groovy"],
      priceBasic: 28.99,
      pricePremium: 48.99,
      priceExclusive: 219.99,
      coverImage: "https://picsum.photos/seed/beat14/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
      description: "Smooth jazz hop beat for chill evenings",
      isPublished: true,
    },
    {
      title: "Epic Cinematic",
      producerId: producer2.profile!.id,
      genre: "Cinematic",
      bpm: 120,
      key: "G",
      duration: 240,
      tags: ["Epic", "Orchestral"],
      priceBasic: 50.99,
      pricePremium: 70.99,
      priceExclusive: 299.99,
      coverImage: "https://picsum.photos/seed/beat15/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
      description: "Epic cinematic beat for trailers",
      isPublished: true,
    },
    {
      title: "Ambient Flow",
      producerId: producer1.profile!.id,
      genre: "Ambient",
      bpm: 60,
      key: "D#m",
      duration: 300,
      tags: ["Relaxing", "Atmospheric"],
      priceBasic: 20.99,
      pricePremium: 40.99,
      priceExclusive: 179.99,
      coverImage: "https://picsum.photos/seed/beat16/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
      description: "Atmospheric ambient beat for meditation",
      isPublished: true,
    },
    {
      title: "Hard Drill",
      producerId: producer2.profile!.id,
      genre: "Drill",
      bpm: 142,
      key: "Am",
      duration: 165,
      tags: ["Dark", "Aggressive"],
      priceBasic: 39.99,
      pricePremium: 64.99,
      priceExclusive: 299.99,
      coverImage: "https://picsum.photos/seed/beat17/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
      description: "Aggressive drill beat with punchy 808s",
      isPublished: true,
    },
    {
      title: "Synthwave Dreams",
      producerId: producer1.profile!.id,
      genre: "Synthwave",
      bpm: 130,
      key: "F#m",
      duration: 210,
      tags: ["Retro", "Energetic"],
      priceBasic: 35.99,
      pricePremium: 55.99,
      priceExclusive: 249.99,
      coverImage: "https://picsum.photos/seed/beat18/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
      description: "Energetic synthwave beat with dreamy vibes",
      isPublished: true,
    },
    {
      title: "Boom Bap Revival",
      producerId: producer2.profile!.id,
      genre: "Boom Bap",
      bpm: 92,
      key: "Em",
      duration: 175,
      tags: ["Classic", "Hip-Hop"],
      priceBasic: 27.99,
      pricePremium: 47.99,
      priceExclusive: 189.99,
      coverImage: "https://picsum.photos/seed/beat19/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
      description: "Classic boom bap beat with old-school vibes",
      isPublished: true,
    },
    {
      title: "Future Groove",
      producerId: producer1.profile!.id,
      genre: "Future Bass",
      bpm: 138,
      key: "G#m",
      duration: 190,
      tags: ["Energetic", "Bass"],
      priceBasic: 40.99,
      pricePremium: 60.99,
      priceExclusive: 259.99,
      coverImage: "https://picsum.photos/seed/beat20/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
      description: "High-energy future bass beat",
      isPublished: true,
    },
    {
      title: "R&B Soul",
      producerId: producer2.profile!.id,
      genre: "R&B",
      bpm: 95,
      key: "F",
      duration: 210,
      tags: ["Smooth", "Melodic"],
      priceBasic: 32.99,
      pricePremium: 54.99,
      priceExclusive: 229.99,
      coverImage: "https://picsum.photos/seed/beat21/400/400",
      audioFile:
        "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      description: "Smooth R&B beat with soulful melodies",
      isPublished: true,
    },
    {
      title: "Chillhop Escape",
      producerId: producer1.profile!.id,
      genre: "Chillhop",
      bpm: 85,
      key: "C",
      duration: 156,
      tags: ["Chill", "Melodic", "Smooth"],
      priceBasic: 29.99,
      pricePremium: 49.99,
      priceExclusive: 199.99,
      coverImage: "https://picsum.photos/seed/beat22/400/400",
      audioFile: "https://example.com/beats/chillhop-escape.mp3",
      description: "A smooth chillhop beat perfect for relaxing",
      isPublished: true,
    },
    {
      title: "Trap Energy",
      producerId: producer2.profile!.id,
      genre: "Trap",
      bpm: 140,
      key: "D#m",
      duration: 180,
      tags: ["Hard", "808", "Dark"],
      priceBasic: 34.99,
      pricePremium: 59.99,
      priceExclusive: 249.99,
      coverImage: "https://picsum.photos/seed/beat23/400/400",
      audioFile: "https://example.com/beats/trap-energy.mp3",
      description: "Heavy hitting trap beat with punchy 808s",
      isPublished: true,
    },
    {
      title: "Summer Chill",
      producerId: producer1.profile!.id,
      genre: "Pop",
      bpm: 120,
      key: "G",
      duration: 195,
      tags: ["Happy", "Upbeat", "Melodic"],
      priceBasic: 24.99,
      pricePremium: 44.99,
      priceExclusive: 179.99,
      coverImage: "https://picsum.photos/seed/beat24/400/400",
      audioFile: "https://example.com/beats/summer-chill.mp3",
      description: "Uplifting pop beat with summer vibes",
      isPublished: true,
    },
    {
      title: "Dark Pulse",
      producerId: producer2.profile!.id,
      genre: "Drill",
      bpm: 138,
      key: "Am",
      duration: 165,
      tags: ["Dark", "Aggressive", "808"],
      priceBasic: 39.99,
      pricePremium: 64.99,
      priceExclusive: 299.99,
      coverImage: "https://picsum.photos/seed/beat25/400/400",
      audioFile: "https://example.com/beats/dark-pulse.mp3",
      description: "Aggressive drill beat with dark atmosphere",
      isPublished: true,
    },
  ];

  // Deduplicate audio URLs and fetch all durations in parallel
  const uniqueUrls = [...new Set(beatDefinitions.map((b) => b.audioFile))];
  console.log(
    `Fetching durations for ${uniqueUrls.length} unique audio files...`,
  );
  const durationMap = Object.fromEntries(
    await Promise.all(
      uniqueUrls.map(async (url) => [url, await getAudioDuration(url)]),
    ),
  );

  for (const beatData of beatDefinitions) {
    const duration = durationMap[beatData.audioFile] || beatData.duration;
    const { duration: _ignored, ...beatWithoutDuration } = beatData;
    const beatId = `beat-${beatData.title.toLowerCase().replace(/\s+/g, "-")}`;

    await prisma.beat.upsert({
      where: { id: beatId },
      update: { ...beatWithoutDuration, duration },
      create: { id: beatId, ...beatWithoutDuration, duration },
    });
  }
}
